[project]
name = "vedelo"
version = "0.1.0"
description = "Vehicle Detection with YOLO"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "huggingface-hub>=1.4.1",
    "matplotlib>=3.10.8",
    "polars>=1.38.1",
    "torch>=2.10.0",
    "ultralytics>=8.4.14",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
    "ty>=0.0.17",
]
export = [
    "colorama>=0.4.6",
    "flatbuffers>=25.12.19",
    "lap>=0.5.13",
    "ml-dtypes>=0.5.4",
    "onnx>=1.20.1",
    "onnxruntime-gpu>=1.24.2",
    "onnxslim>=0.1.85",
    "protobuf>=6.33.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["vedelo"]
include = ["static"]

[tool.ty.rules]
no-matching-overload = "ignore"
